### ISSUE TITLE
Make it easy to use the system without the kafka or simplify local setup

### ISSUE THREAD

**Issue by andreyrozumnyi** [nirdizati/nirdizati-runtime#17]
Right now we have a branch with Kafka which will become out of sync very fast. So we need to make it possible to use the system whether without Kafka or simplify local development setup. Currently, development setup is already a problem, so it would not be good to make it even harder.

**Comment by verenich** [comment]
can we close this issue now? The current version in the master branch has been tested to work with and without kafka, and either setup is documented in README files.
